import { expect, test, type Page } from '@playwright/test';
const zone = (page: Page, id: string) => page.locator(`[data-quadrant="${id}"]`);
async function add(page: Page, id: string, title: string) {
  await zone(page, id).getByRole('button', { name: /添加任务到/ }).click();
  const input = zone(page, id).getByRole('textbox');
  await input.fill(title); await input.press('Enter');
  await expect(zone(page, id).getByRole('button', { name: title, exact: true })).toBeVisible();
}
test('main and widget share add, edit, completion, deletion and reload', async ({ page, context }) => {
  await page.goto('/');
  const widget = await context.newPage(); await widget.setViewportSize({ width: 380, height: 360 }); await widget.goto('/?widget');
  await add(widget, 'plan', 'Read & reflect 阅读');
  await expect(zone(page, 'plan').locator('.task-title')).toHaveText(['Read & reflect 阅读']);
  await page.getByRole('button', { name: 'Read & reflect 阅读', exact: true }).click();
  await page.getByRole('textbox').fill('准备下一版设计'); await page.getByRole('textbox').press('Enter');
  await expect(widget.getByRole('button', { name: '准备下一版设计', exact: true })).toBeVisible();
  await widget.getByRole('checkbox', { name: '完成 准备下一版设计' }).click();
  await expect(page.getByRole('checkbox', { name: '取消完成 准备下一版设计' })).toHaveAttribute('aria-checked', 'true');
  await add(page, 'plan', '未完成优先');
  await expect(zone(widget, 'plan').locator('.widget-task-title')).toHaveText(['未完成优先', '准备下一版设计']);
  await widget.getByRole('checkbox', { name: '取消完成 准备下一版设计' }).click();
  await expect(page.getByRole('checkbox', { name: '完成 准备下一版设计' })).toBeVisible();
  await widget.getByRole('button', { name: '准备下一版设计', exact: true }).hover();
  await widget.getByRole('button', { name: '删除 准备下一版设计' }).click();
  await expect(zone(page, 'plan').locator('.task-title')).toHaveText(['未完成优先']);
  await widget.reload();
  await expect(zone(widget, 'plan').locator('.widget-task-title')).toHaveText(['未完成优先']);
});
test('widget inline input supports Escape, blur, IME and pin feedback', async ({ page }) => {
  await page.goto('/?widget');
  await zone(page, 'do').locator('.widget-add').click();
  await page.getByRole('textbox').fill('取消的输入'); await page.getByRole('textbox').press('Escape');
  await expect(zone(page, 'do').locator('.widget-task')).toHaveCount(0);
  await zone(page, 'do').locator('.widget-add').click();
  const input = page.getByRole('textbox'); await input.fill('中文输入法');
  await input.evaluate(el => el.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', isComposing: true, bubbles: true })));
  await expect(input).toBeVisible();
  await page.locator('h2').first().click();
  await expect(zone(page, 'do').locator('.widget-task-title')).toHaveText(['中文输入法']);
  const pin = page.getByRole('button', { name: '始终置顶' }); await pin.click();
  await expect(pin).toHaveAttribute('aria-pressed', 'true'); await pin.click(); await expect(pin).toHaveAttribute('aria-pressed', 'false');
});
test('widget balanced grid, long content, light, dark and minimum size screenshots', async ({ page }, info) => {
  await page.setViewportSize({ width: 380, height: 360 }); await page.goto('/?widget');
  await page.screenshot({ path: info.outputPath('widget-empty.png') });
  await add(page, 'do', '核对交付清单'); await add(page, 'do', '确认今天的安排');
  await add(page, 'plan', 'Read & reflect 阅读'); await add(page, 'plan', '打磨下一版原型');
  await add(page, 'delegate', '回复供应商邮件'); await add(page, 'eliminate', '整理下载文件');
  await page.getByRole('checkbox', { name: '完成 确认今天的安排' }).click();
  await expect(zone(page, 'do').locator('.completed .widget-task-title')).toHaveCSS('color', 'rgb(144, 146, 139)');
  await page.mouse.move(375, 355);
  await page.screenshot({ path: info.outputPath('widget-light.png') });
  await page.emulateMedia({ colorScheme: 'dark' });
  await expect(page.locator('.widget-shell')).toHaveCSS('color', 'rgb(223, 223, 216)');
  await expect(zone(page, 'plan').locator('.widget-task-title').first()).toHaveCSS('color', 'rgb(223, 223, 216)');
  await page.screenshot({ path: info.outputPath('widget-dark.png') });
  await page.setViewportSize({ width: 340, height: 300 });
  await page.screenshot({ path: info.outputPath('widget-minimum.png') });
  const boxes = await page.locator('.widget-quadrant').evaluateAll(elements => elements.map(el => { const r = el.getBoundingClientRect(); return { x: r.x, y: r.y, width: r.width, height: r.height }; }));
  expect(boxes[0].width).toBe(boxes[1].width); expect(boxes[0].height).toBe(boxes[2].height);
  expect(boxes[0].y).toBe(boxes[1].y); expect(boxes[2].y).toBe(boxes[3].y);
  await page.evaluate(() => { localStorage.setItem('four-quadrants-browser-preview-v1', JSON.stringify(Array.from({ length: 80 }, (_, i) => ({ id: `long-${i}`, title: i === 0 ? '检查中文 English 混排与长任务截断 '.repeat(10) : `等待处理的任务 ${i}`, completed: false, quadrant: 'do' })))); });
  await page.reload();
  await expect(zone(page, 'do').locator('.widget-task')).toHaveCount(80);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(await zone(page, 'do').locator('.widget-scroll').evaluate(el => el.scrollHeight > el.clientHeight)).toBe(true);
  await expect(zone(page, 'do').locator('.widget-add')).toBeVisible();
  await page.screenshot({ path: info.outputPath('widget-overflow.png') });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await expect(page.locator('.widget-action').first()).toHaveCSS('transition-duration', '0s');
});
